# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

name: Copy cloud-docs for TFE
description: Copy docs/nav-data/assets from source dir to target dir
runs:
  using: 'node20'
  main: 'out/index.js'
inputs:
  source_path:
    required: true
    description: 'The path to source HCP terraform files from'
  target_path:
    required: true
    description: 'The path to copy over HCP terraform files to'
  new_TFE_version:
    required: false
    description: 'The new TFE version to create and copy docs into.'
