# Copyright IBM Corp. 2024, 2026
# SPDX-License-Identifier: BUSL-1.1

# TECH WRITERS READ THIS!!
# 1. Create a new label in format "forward-port:<unique-label-value>"
# 2. Update your product's forward port config entry.
# The config entry key is the "<unique-label-value>" in your label.
# Ex:  "forward-port:nomad" label -> "nomad" config entry key.
# Ex2: "forward-port:boundary-1.0" -> "boundary-1.0" config entry key.
# Note that ":" after the config entry key is YAML syntax, 
#               not part of <unique-label-value>
# Config entry values:
# Every entry requires the following:
# sourceVersionFolder: Most often the current release folder
# targetProduct: The exact name of your content product folder. 
#                For example, "boundary" not "Boundary"
# targetBranch: The branch to open the PR against
#               Most often the upcoming release branch
# targetVersionFolder: Folder to copy changes into
#                      Most often the upcoming release version
# Refer to scripts/forward-port/forward-port-README.md for workflow details
# and scenarios, including how to using multiple labels for different scenarios


# ── Testing ──────────────────────────────────────────────────────────────────
tf-forward-porting-testing:
  sourceVersionFolder: v1.14.x
  targetProduct: terraform-forward-port-testing
  targetBranch: rn-forward-porting-test-rc
  targetVersionFolder: v1.15.x

# ── Boundary ─────────────────────────────────────────────────────────────────
boundary-1.0-forward-port:
  sourceVersionFolder: v0.21.x
  targetProduct: boundary
  targetBranch: main
  targetVersionFolder: v1.0.x

# ── Consul ───────────────────────────────────────────────────────────────────
consul:
  sourceVersionFolder: v2.0.x
  targetProduct: consul
  targetBranch: consul/2.1.0
  targetVersionFolder: v2.1.x

# ── HCP ──────────────────────────────────────────────────────────────────────
hcp-placeholder-label:
  sourceVersionFolder: v1.0.0
  targetProduct: hcp-docs
  targetBranch: hcp-placeholder-test
  targetVersionFolder: v1.1.0

# ── Nomad ────────────────────────────────────────────────────────────────────
<<<<<<< HEAD
nomad-2.1-forward-port:
=======
nomad:
>>>>>>> main
  sourceVersionFolder: v2.0.x
  targetProduct: nomad
  targetBranch: nomad/2.1.0
  targetVersionFolder: v2.1.x

# ── Packer ───────────────────────────────────────────────────────────────────
packer-placeholder-label:
  sourceVersionFolder: v1.0.0
  targetProduct: packer
  targetBranch: packer-placeholder-test
  targetVersionFolder: v1.1.0

# ── Sentinel ─────────────────────────────────────────────────────────────────
sentinel-placeholder-label:
  sourceVersionFolder: v1.0.0
  targetProduct: sentinel
  targetBranch: sentinel-placeholder-test
  targetVersionFolder: v1.1.0

# ── Terraform Enterprise ─────────────────────────────────────────────────────
tfe-placeholder-label:
  sourceVersionFolder: v1.0.0
  targetProduct: terraform-enterprise
  targetBranch: tfe-placeholder-test
  targetVersionFolder: v1.1.0

# ── Vagrant ──────────────────────────────────────────────────────────────────
vagrant-placeholder-label:
  sourceVersionFolder: v1.0.0
  targetProduct: vagrant
  targetBranch: vagrant-placeholder-test
  targetVersionFolder: v1.1.0

# ── Vault ────────────────────────────────────────────────────────────────────
vault-placeholder-label:
  sourceVersionFolder: v1.0.0
  targetProduct: vault
  targetBranch: vault-placeholder-test
  targetVersionFolder: v1.1.0

vault-placeholder-test-label:
  sourceVersionFolder: v1.0.0
  targetProduct: vault
  targetBranch: vault-placeholder-test
  targetVersionFolder: v1.1.0
