Boundary:
  targetBranch: TF-next
  targetVersion: v1.1.0

Consul:
  targetBranch: TF-next
  targetVersion: v1.1.0

HCP:
  targetBranch: TF-next
  targetVersion: v1.1.0

Nomad:
  targetBranch: TF-next
  targetVersion: v1.1.0

Packer:
  targetBranch: TF-next
  targetVersion: v1.1.0

Sentinel:
  targetBranch: TF-next
  targetVersion: v1.1.0

Terraform CE:
  targetBranch: TF-next
  targetVersion: v1.1.0

Terraform agents:
  targetBranch: TF-next
  targetVersion: v1.1.0

HCP Terraform:
  targetBranch: TF-next
  targetVersion: v1.1.0

Terraform Enterprise:
  targetBranch: TF-next
  targetVersion: v1.1.0

Terraform MCP Server:
  targetBranch: TF-next
  targetVersion: v1.1.0

Terraform migrate:
  targetBranch: TF-next
  targetVersion: v1.1.0

TF Plugin Framework:
  targetBranch: TF-next
  targetVersion: v1.1.0

Vagrant:
  targetBranch: TF-next
  targetVersion: v1.1.0

Vault:
  targetBranch: TF-next
  targetVersion: v1.1.0

Vault IC:
  targetBranch: TF-next
  targetVersion: v1.1.0

Vault Radar:
  targetBranch: TF-next
  targetVersion: v1.1.0

WAF:
  targetBranch: TF-next
  targetVersion: v1.1.0

Waypoint:
  targetBranch: TF-next
  targetVersion: v1.1.0
