"Terraform":
- any:
  - changed-files:
    - any-glob-to-any-file: 'content/terraform/*'
    - any-glob-to-any-file: 'content/terraform-enterprise/*'
    - any-glob-to-any-file: 'terraform-plugin-mux/*'
    - any-glob-to-any-file: 'terraform-cdk/*'
    - any-glob-to-any-file: 'terraform-migrate/*'
    - any-glob-to-any-file: 'terraform-plugin-sdk/*'
    - any-glob-to-any-file: 'terraform-docs-agents/*'
    - any-glob-to-any-file: 'terraform-plugin-framework/*'
    - any-glob-to-any-file: 'terraform-plugin-testing/*'
    - any-glob-to-any-file: 'terraform-docs-common/*'
    - any-glob-to-any-file: 'terraform-plugin-log/*'
"Vault Docs":
- any:
  - changed-files:
    - any-glob-to-any-file: 'content/vault/*'
"WAF":
- any:
  - changed-files:
    - any-glob-to-any-file: 'well-architected-framework/*'
