# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

# Add 'Boundary' label to changes under 'content/boundary'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Boundary        | Default; applies to all doc updates
# Boundary        | Updates on HCP Boundary in hcp-docs directory

Boundary:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/boundary/**',
        'content/hcp-docs/content/docs/boundary/**'
      ]

# Add 'Consul' label to changes under 'content/consul'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Consul          | Default; applies to all doc updates
# Consul          | Updates on HCP Consul in hcp-docs directory

Consul:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/consul/**',
        'content/hcp-docs/content/docs/consul/**'
      ]

# Add 'HCP' label to changes under 'content/hcp-docs'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# HCP             | Default; applies to all doc updates

HCP:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/hcp-docs/**'
      ]

# Add 'Nomad' label to changes under 'content/nomad'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Nomad             | Default; applies to all doc updates

Nomad:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/nomad/**'
      ]

# Add 'Packer' label to changes under 'content/packer'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Packer          | Default; applies to all doc updates
# Packer          | Updates on HCP Packer in hcp-docs directory

Packer:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/packer/**',
        'content/hcp-docs/content/docs/packer/**'
      ]

# Add 'Sentinel' label to changes under 'content/sentinel'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Sentinel        | Default; applies to all doc updates

Sentinel:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/sentinel/**'
      ]

# Add a Terraform label to changes under the related folders:
#
# Folder                      | Labels
# --------------------------- | ------------------------------------------------
# terraform                   | Terraform CE
# terraform-cdk               | None
# terraform-docs-agents       | Terraform agents
# terraform-docs-common       | HCP Terraform
# terraform-enterprise        | Terraform Enterprise
# terraform-migrate           | Terraform migrate
# terraform-plugin-framework  | TF Plugin Framework
# terraform-plugin-log        | None
# terraform-plugin-mux        | None
# terraform-plugin-sdk        | None
# terraform-plugin-testing    | None

Terraform CE:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform/**'
      ]

Terraform agents:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-docs-agents/**'
      ]

HCP Terraform:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-docs-common/**'
      ]

Terraform Enterprise:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-enterprise/**'
      ]

Terraform MCP Server:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-mcp-server/**'
      ]

Terraform migrate:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-migrate/**'
      ]

TF Plugin Framework:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/terraform-plugin-framework/**'
      ]

# Add 'Vagrant' label to changes under 'content/vagrant'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Vagrant         | Default; applies to all doc updates
# Vagrant         | Updates on HCP Vagrant in hcp-docs directory

Vagrant:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/vagrant/**',
        'content/hcp-docs/content/docs/vagrant/**'
      ]

# Add 'Vault' label to changes under 'content/vault', and 'content/hcp-docs/content/docs/vault'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Vault           | Default; applies to all doc updates
# Vault           | Updates on HCP Vault Dedicated in hcp-docs directory
# Vault IC update | Updates on "Important changes" related docs

Vault:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/vault/**',
        'content/hcp-docs/content/docs/vault/**'
      ]

Vault IC:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/vault/global/partials/important-changes/**',
        'content/vault/*/content/docs/updates/change-tracker.mdx',
        'content/vault/*/content/docs/updates/important-changes.mdx',
        'content/vault/*/content/docs/updates/lts-tracker.mdx'
      ]

# Add 'Vault Radar' label to changes under 'content/hcp-docs/content/docs/vault-radar'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Vault Radar     | Default; applies to all doc updates

Vault Radar:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/hcp-docs/content/docs/vault-radar/**'
      ]

# Add 'WAF' label to changes under 'content/well-architected-framework'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# WAF             | Default; applies to all doc updates

WAF:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/well-architected-framework/**'
      ]

# Add 'Waypoint' label to changes under 'content/hcp-docs/content/docs/waypoint'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Waypoint        | Default; applies to all doc updates

Waypoint:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/hcp-docs/content/docs/waypoint/**'
      ]

# Add 'Runtime' label to changes under 'content/consul', 'content/nomad', 'content/hcp-docs/content/docs/cli' and 'content/hcp-docs/content/docs/hcp'
#
# Label           | Rule
# --------------- | ------------------------------------------------------------
# Runtime         | Default; applies to all doc updates
# Runtime         | Updates to Consul documentation
# Runtime         | Updates to Nomad documentation
# Runtime         | Updates to HCP CLI documentation
# Runtime         | Updates to HCP platform documentation


Runtime:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        'content/consul/**',
        'content/nomad/**',
        'content/hcp-docs/content/docs/cli/**',
        'content/hcp-docs/content/docs/hcp/**'
      ]
