services:
  dev-portal:
    image: 'hashicorp/dev-portal:latest'
    container_name: dev-portal
    ports:
      - ${DEV_PORTAL_PORT}:${DEV_PORTAL_PORT}
    depends_on:
      - experimental-docs-api
    environment:
      - MKTG_CONTENT_DOCS_API=https://content.hashicorp.com
      - UNIFIED_DOCS_API=http://experimental-docs-api:${UNIFIED_DOCS_PORT}
      - HASHI_ENV=unified-docs-sandbox
      - NODE_ENV=development
    profiles: [unified-docs]

  experimental-docs-api:
    build: .
    container_name: experimental-docs-api
    ports:
      - ${UNIFIED_DOCS_PORT}:${UNIFIED_DOCS_PORT}
    environment:
      - IS_DOCKER=true
      - DEV_PORTAL_URL=http://dev-portal:${DEV_PORTAL_PORT}
    volumes:
      - ./content:/server/content
