services:
  dev-portal-migration:
    image: 'hashicorp/dev-portal:latest'
    container_name: dev-portal-migration
    ports:
      - ${DEV_PORTAL_PORT}:${DEV_PORTAL_PORT}
    depends_on:
      - experimental-docs-api
    environment:
      - MKTG_CONTENT_DOCS_API=https://content.hashicorp.com
      - UNIFIED_DOCS_API=http://experimental-docs-api:${UNIFIED_DOCS_PORT}
    profiles: [migration]
  dev-portal-unified:
    image: 'hashicorp/dev-portal:latest'
    container_name: dev-portal-unified
    ports:
      - ${DEV_PORTAL_PORT}:${DEV_PORTAL_PORT}
    depends_on:
      - experimental-docs-api
    environment:
      - MKTG_CONTENT_DOCS_API=http://experimental-docs-api:${UNIFIED_DOCS_PORT}
      - UNIFIED_DOCS_API=http://experimental-docs-api:${UNIFIED_DOCS_PORT}
    profiles: [unified-docs]
  experimental-docs-api:
    build: .
    container_name: experimental-docs-api
    ports:
      - ${UNIFIED_DOCS_PORT}:${UNIFIED_DOCS_PORT}
    develop:
      watch:
        - action: sync
          path: .
          target: /server
