services:
  dev-portal:
    image: "hashicorp/dev-portal:latest"
    container_name: dev-portal
    ports:
      - "3000:3000"
    depends_on:
      - experimental-docs-api
    environment:
      - NEXT_PUBLIC_LEARN_API_BASE_URL=http://experimental-docs-api:8080
  
  experimental-docs-api:
      build: .
      container_name: experimental-docs-api
      ports:
        - "8080:8080"
