[build]
  base = "website"
  command = "npm run generate-changelog; npm run static"
  publish = "out"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/"
  to = "/sentinel"
  status = 301
