# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

blank_issues_enabled: false
contact_links:
   - name: Boundary docs issue
     url: https://github.com/hashicorp/boundary/issues
     about: Create a Boundary docs issue in the Boundary repository.
   - name: Consul docs issue
     url: https://github.com/hashicorp/consul/issues
     about: Create a Consul docs issue in the Consul repository.
   - name: Nomad docs issue
     url: https://github.com/hashicorp/nomad/issues
     about: Create a Nomad docs issue in the Nomad repository.
   - name: Packer docs issue
     url: https://github.com/hashicorp/packer/issues
     about: Create a Packer docs issue in the Packer repository. 
   - name: Terraform docs issue
     url: https://github.com/hashicorp/terraform/issues
     about: Create a Terraform docs issue in the Terraform repository.
   - name: Vagrant docs issue
     url: https://github.com/hashicorp/vagrant/issues
     about: Create a Vagrant docs issue in the Vagrant repository.
   - name: Vault docs issue
     url: https://github.com/hashicorp/vaultissues
     about: Create a Vault docs issue in the Vault repository.
 