name: Documentation Issue
description: |-
  HashiCorp Product Documentation Issue
title: "[Content Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request changes to HashiCorp product documentation.        
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: |-
        What product content is this for?
      options:
        - Boundary
        - Consul
        - HashiCorp Cloud Platform 
        - Nomad    
        - Packer
        - Sentinel
        - Terraform
        - Vagrant
        - Vault
        - Waypoint
        - Well-Architected Framework        
        - Other product
        - No product
      default: 6
    validations:
      required: true
  - type: dropdown
    id: issueType
    attributes:
      label: Issue type
      description: |-
        Is this issue about a bug such as broken instructions or page 404s? Or are you requesting new content?
      options:
        - Bug
        - New content
        - Other issue
      default: 0
    validations:
      required: false
  - type: textarea
    id: what
    attributes:
      label: |-
        Describe your issue to request changes to the content on developer.hashicorp.com. Be specific and provide as much detail as possible. Include page URLs and screenshots if applicable.
      description: 
      placeholder: In the documentation for...
      value: "In the documentation for..."
    validations:
      required: true
