name: Documentation Issue
description: |-
  HCP Waypoint, Sentinel, Well-Architected Framework, HashiCorp Cloud Platform (Admin, CLI, IAM, Network, Security sections)
title: "[Content Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Use this form to create a docs issue for HCP Waypoint, Sentinel, Well-Architected Framework, and HashiCorp Cloud Platform (Admin, CLI, IAM, Network, Security sections). 
        **Create docs issues for all other products in the product's repository.** 
        On this form, click the **Cancel** button to close this window. Then click the **New Issue** button in the GitHub web UI. Finally, click the link to the desired product repository.
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: |-
        What product content is this for? If you do not see your product in the pick list, click the **Cancel** button to close this window. Then click the **New Issue** button again. Finally, click the link to the correct product repository.
      options:
        - HashiCorp Cloud Platform     
        - HCP CLI
        - HCP Waypoint
        - Sentinel
        - Well-Architected Framework        
        - Other product
        - No product
      default: 0
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: |-
        What content updates would you like us to do? Be specific and provide as much detail as possible. Include specific page URLs if applicable.
      description: 
      placeholder: Please document how to... 
      value: "Please document how to..."
    validations:
      required: true

