name: Documentation Issue
description: |-
  HashiCorp Product Documentation Issue
title: "[Content Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Use this form to create a docs issue for HashiCorp product documentation.        
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: |-
        What product content is this for?
      options:
        - Boundary
        - Consul
        - HashiCorp Cloud Platform 
        - Nomad    
        - Packer
        - Sentinel
        - Terraform
        - Vagrant
        - Vault
        - Waypoint
        - Well-Architected Framework        
        - Other product
        - No product
      default: 6
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Issue category
      description: |-
        Documentation or tutorial issue?
      options:
        - Documentation
        - Tutorial
      default: 0
    validations:
      required: true
  - type: dropdown
    id: issueType
    attributes:
      label: Issue type
      description: |-
        Is this issue about a bug with the website or product instructions? Or are you requesting new content?
      options:
        - Bug
        - New content
        - Other
      default: 0
    validations:
      required: false
  - type: textarea
    id: what
    attributes:
      label: |-
        Describe your issue or request changes to the content on developer.hashicorp.com. Be specific and provide as much detail as possible. Include specific page URLs if applicable.
      description: 
      placeholder: Please document how to... 
      value: "Please document how to..."
    validations:
      required: true
