name: Documentation Issue
description: |-
  HCP Waypoint, Sentinel, Well-Architected Framework, HashiCorp Cloud Platform (Admin, CLI, IAM, Network, Security sections)
title: "[Content Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Use this form to create a docs issue for HashiCorp product documentation.        
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: |-
        What product content is this for?
      options:
        - Boundary
        - Consul
        - HashiCorp Cloud Platform 
        - Nomad    
        - Packer
        - Sentinel
        - Terraform
        - Vagrant
        - Vault
        - Waypoint
        - Well-Architected Framework        
        - Other product
        - No product
      default: 6
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: |-
        What content updates would you like us to do? Be specific and provide as much detail as possible. Include specific page URLs if applicable.
      description: 
      placeholder: Please document how to... 
      value: "Please document how to..."
    validations:
      required: true
