# Copyright IBM Corp. 2024, 2026
# SPDX-License-Identifier: BUSL-1.1

name: HashiCorp Validated Design Feedback
description: Provide feedback on a HashiCorp Validated Design guide.
title: "Short summary of your feedback"
body:
  - type: markdown
    attributes:
      value: |
        Use this form to provide feedback on a HashiCorp Validated Design guide.
  - type: dropdown
    id: guide
    attributes:
      label: Product / Guide
      description: Which validated design guide is your feedback for?
      options:
        - Boundary — Installation Guide
        - Boundary — Administration Guide
        - Boundary — User Guide
        - Consul — Installation Guide
        - Consul — Administration Guide
        - Consul — User Guide
        - Nomad — Installation Guide
        - Nomad — Administration Guide
        - Nomad — User Guide
        - Terraform — Installation Guide
        - Terraform — Administration Guide
        - Terraform — User Guide
        - Vault — Installation Guide
        - Vault — Administration Guide
        - Vault — User Guide
        - Vault Radar — Administration Guide
        - Vault Radar — User Guide
        - Not applicable
    validations:
      required: true
  - type: input
    id: page_url
    attributes:
      label: Page URL
      description: URL of the specific page your feedback relates to.
      placeholder: "https://developer.hashicorp.com/validated-designs/..."
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Describe your feedback in as much detail as possible.
      placeholder: "On this page..."
    validations:
      required: true
