#  Copyright (c) HashiCorp, Inc.
#  SPDX-License-Identifier: BUSL-1.1

name: Re-load dev portal
description: 'Re-load dev portal for changed files'
inputs:
  base_sha:
    description: 'Base SHA for changed files comparison'
    required: true
    type: string
  head_sha:
    description: 'Head SHA for changed files comparison'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get changed files in the content/ subdirectories
      id: changed-files
      uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
      with:
        files: |
          content/**/*.mdx
        base_sha: ${{ inputs.base_sha }}
        sha: ${{ inputs.head_sha }}

    - name: Print changed files
      run: |
        echo "Changed files:"
        echo ${{ steps.changed-files.outputs.all_changed_files }}

    - name:
      if: steps.changed-files.outputs.all_changed_files == ''
      run: |
        echo "No changed files found, redeploying dev-portal in case of api changes"
        curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_PROD }}
        exit 0

    - name: Map files to URLs
      id: map-files
      run: |
        FILES_URLS=$(node ./scripts/map-files-to-urls.mjs ${{ needs.get-changed-files.outputs.changed_files }})
        echo "FILES_URLS=$FILES_URLS" >> $GITHUB_OUTPUT
  
    - name: Print urls
      run: echo ${{ steps.map-files.outputs.FILES_URLS }}

    - name: Revalidate paths
      id: revalidate-paths
      env:
        url: 'https://developer.hashicorp.com/api/revalidate/paths'
        auth: 'Authorization: Bearer ${{ secrets.REVALIDATE_TOKEN }}'
      run: |
        curl -X POST "${{ env.url }}" \
          -H "${{ env.auth }}" \
          -H "Content-Type: application/json" \
          -d '{"paths": ${{ steps.map-files.outputs.FILES_URLS }} }'
