name: 'Get Vercel Preview URL'
description: 'Computes the Vercel Preview URL based on project name, branch name, and scope slug'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  project-name:
    description: 'The name of the Vercel project'
    required: true
  scope:
    description: 'The scope slug for the Vercel project'
    required: true
outputs:
  preview-url:
    description: 'The computed Vercel Preview URL'