name: Get Vercel Preview URL
description: Fetches the latest Vercel preview, inspector URL, and created UTC for the specified project's deployment
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  development_type:
    description: 'The type of Vercel deployment to fetch'
    required: true
    default: 'unified-docs-api' # or 'url'
  team_id:
    description: 'The Vercel team ID'
    required: true
  vercel_token:
    description: 'The Vercel token'
    required: true

  # required by type=url
  deployment_url:
    description: 'The Vercel deployment URL'
    required: false

  # required by type=unified-docs-api
  project_id:
    description: 'The Vercel project ID'
    required: false
  github_branch_name:
    description: 'The GitHub branch name'
    required: false
outputs:
  preview-url:
    description: 'The URL of the latest Vercel preview for Unified Docs'
  inspector-url:
    description: 'The URL of the latest Vercel inspector for Unified Docs'
  created_utc:
    description: 'The pretty UTC string of when the preview was created'
