name: Get Vercel Preview URL
description: Fetches the latest Vercel preview, inspector URL, and created utc for the specified project's deployment
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  project_id:
    description: 'The Vercel project ID'
    required: true
  team_id:
    description: 'The Vercel team ID'
    required: true
  vercel_token:
    description: 'The Vercel token'
    required: true
outputs:
  preview-url:
    description: 'The URL of the latest Vercel preview for Unified Docs'
  inspector-url:
    description: 'The URL of the latest Vercel inspector for Unified Docs'
  created_utc:
    description: 'The pretty UTC string of when the preview was created'
