name: Get Vercel Preview URL
description: Fetches the latest Vercel preview URL for the specified project
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  project_id:
    description: 'The Vercel project ID'
    required: true
  team_id:
    description: 'The Vercel team ID'
    required: true
  vercel_token:
    description: 'The Vercel token'
    required: true
outputs:
  preview-url:
    description: 'The URL of the latest Vercel preview for Unified Docs'