# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

name: Map Files to URLs
description: Maps files to their respective URLs
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  files:
    description: 'The list of files'
    required: true

outputs:
  paths:
    description: 'The list of paths'