name: Algolia Sync - Production

env:
  ALGOLIA_API_KEY_REPLACE_INDEX_PROD: ${{ secrets.ALGOLIA_API_KEY_REPLACE_INDEX_PROD }}
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_UDR_INDEX_NAME_PROD: ${{ secrets.ALGOLIA_UDR_INDEX_NAME_PROD }}

on:
  push:
    branches:
      - 'main'

jobs:
  setup:
    name: 'Setup Algolia Sync'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20

      - run: npm ci
      - run: npm run prebuild
      - run: npm run algolia
