name: Algolia Sync - Production

on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/**/**/docs/**/*.mdx'

jobs:
  setup-and-update-algolia:
    name: Setup and Update Algolia
    runs-on: ubuntu-latest
    if: github.repository == 'hashicorp/web-unified-docs'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: 'npm'
          node-version-file: 'package.json'

      - run: npm i
      - run: npm run prebuild
      - run: npm run algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY_PROD }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME_PROD}}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
