name: Broken Link Check (inline)

on:
  workflow_dispatch:
    inputs:
      preview_url:
        description: 'Preview URL from dev-portal-preview workflow'
        required: true
        type: string
      pr_number:
        description: 'PR number for commenting results'
        required: true
        type: string
      base_sha:
        description: 'Base SHA for changed files comparison'
        required: true
        type: string
      head_sha:
        description: 'Head SHA for changed files comparison'
        required: true
        type: string

permissions:
  pull-requests: write
  checks: read
  contents: read
  actions: read

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          
      - name: Get changed files in the content/ subdirectories
        id: changed-files
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
        with:
          files: |
            content/**/*.mdx
          base_sha: ${{ inputs.base_sha }}
          sha: ${{ inputs.head_sha }}

      - name: Print changed files
        run: |
          echo "Changed files:"
          echo ${{ steps.changed-files.outputs.all_changed_files }}

  linkChecker:
    name: link checker
    needs: [get-changed-files]
    if: needs.get-changed-files.outputs.changed_files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6 # v2.3.0
        with:
          args: ${{ needs.get-changed-files.outputs.changed_files }} --base-url ${{ inputs.preview_url }} --exclude-all-private --exclude '\.(svg|gif|jpg|png)' --accept 403,200,429,401 --timeout=60 --max-concurrency 24 --no-progress --verbose
          jobSummary: true
          # Fail GitHub action at this step when broken links are found?
          fail: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Append text to beginning of Lychee output file if broken links found
        # Append lychee output file under any lychee condition
        if: env.lychee_exit_code != 0
        run: |
          sed -i '1s/^/The GitHub action "Broken Link Check" has completed running on all content within the scope of this PR.\n/' ./lychee/out.md

      # Comment on PR with lychee output; subsequent runs will modify existing PR comment with latest results
      - name: Comment on PR with GitHub action context
        if: env.lychee_exit_code != 0
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          header: Link Checker Report
          path: ./lychee/out.md
          number: ${{ inputs.pr_number }}

      # Fail github action if lychee exit code is anything other than the success code (0)
      - name: lychee exit code check
        if: env.lychee_exit_code != 0
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
              core.setFailed('lychee failed with exit code ${{env.lychee_exit_code}}')

      # If all previous Github actions run (indicating success), this one will run and overwrite the comment with a success message
      - name: Clean up PR comments if all previous steps succeed
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          header: Link Checker Report
          message: |
            No broken links found! ✅
          number: ${{ inputs.pr_number }}

