name: Broken Link Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Run lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@ec3ed119d4f44ad2673a7232460dc7dff59d2421 # v1.8.0
        with:
          args: ./content/ --base https://developer.hashicorp.com/ --exclude-all-private --exclude '\.(svg|gif|jpg|png)' --accept 403,200,429,401 --max-concurrency=24 --no-progress --verbose
          # Fail GitHub action when broken links are found?
          fail: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Close Previous Link Checker Report GitHub Issue with label 'link-checker-report'
        if: env.lychee_exit_code != 0
        uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          # Only issues with ALL these labels are checked
          only-issue-labels: link-checker-report
          # Idle number of days before marking issues stale
          # Issues must be marked stale before it can be closed
          days-before-issue-stale: 0
          # Idle number of days before closing old issues
          days-before-issue-close: 0
          close-issue-message: "This issue was closed because an updated Link Checker Report has been generated."
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Issue From lychee output file
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94 # v5.0.0
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: link-checker-report
