name: 'Check Copyright Headers'

on:
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.mjs'
  push:
    branches: ['main']

jobs:
  check-headers:
    name: 'Check Copyright Headers'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install copywrite
        uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3

      - name: Validate Header Compliance
        run: copywrite headers --plan
