name: TESTING - Create release branch PR
run-name: 🚀 Creating ${{ github.event.inputs.product }} release PR

permissions: 
  contents: write

on: 
  workflow_dispatch:
    inputs:
      product:
        required: true
        default: vault
        description: >-
          Product slug (e.g., vault, hcp)
      branch-name:
        required: true
        description: >-
          Release branch name without product prefix.

env:
  RELEASE_BRANCH: "${{ github.event.inputs.product }}/${{ github.event.inputs.branch-name }}"
  MERGE_TARGET:   "main"
  LABELS:         "${{ inputs.product }}-docs"
  PR_TITLE:       "[PUBLISH] ${{ github.event.inputs.product }}/${{ github.event.inputs.branch-name }}"
  PR_BODY:        "Publication PR created by Github action"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging data
        run: |
          echo "🚧 ${{ github.repository }} - Creating PR"
          echo "    - Release branch: $RELEASE_BRANCH"
          echo "    - Merge target:   $MERGE_TARGET"
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create pull request
        run: |
          gh pr create          \
            -B $MERGE_TARGET    \
            -H $RELEASE_BRANCH  \
            --label "$LABELS"   \
            --title "$PR_TITLE" \
            --body "$PR_BODY"
        env:
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
      - name: Wrap-up
        run: echo "🍏 This job's status is ${{ job.status }}."
