name: Deploy Unified Docs Previews for PR
run-name: 'Builds dev-portal preview for PR ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})'

on: pull_request

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-dev-portal-preview:
    name: Deploy Dev Portal Preview
    runs-on: ubuntu-latest
    steps:
      - name: Initial comment on PR
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
        with:
          header: preview-notice
          message: |
            ## Deploying previews...

            | Status | Preview |
            | :------ | :------ |
            | 🔄 In progress | ([Inspect](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})) |

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # can't cache since we are working with 2 different projects

      - name: Setup Vercel CLI
        run: npm i --global vercel@latest

      - name: Checkout Unified Docs Preview (API)
        uses: actions/checkout@v4
        with:
          repository: hashicorp/web-unified-docs
          path: ./unified-docs-api-preview
          ref: ${{ github.ref }}

      - name: Deploy Unified Docs Preview (API)
        id: deploy-unified-docs
        working-directory: ./unified-docs-api-preview
        run: |
          unified_docs_preview_url=$(vercel deploy --scope=hashicorp --token=$VERCEL_TOKEN)
          echo "unified-docs-preview-url=$unified_docs_preview_url" >> $GITHUB_OUTPUT

      - name: Checkout hashicorp/dev-portal (Frontend)
        uses: actions/checkout@v4
        with:
          repository: hashicorp/dev-portal
          path: ./unified-docs-frontend-preview

      - name: Pull preview environment
        working-directory: ./unified-docs-frontend-preview
        run: vercel pull --yes --environment=preview --scope=hashicorp --token=$VERCEL_TOKEN

      - name: Build dev-portal
        env:
          HASHI_ENV: preview
          UNIFIED_DOCS_API: 'https://${{ steps.deploy-unified-docs.outputs.unified-docs-preview-url }}'
          IS_CONTENT_PREVIEW: true
        working-directory: ./unified-docs-frontend-preview
        run: vercel build --token=$VERCEL_TOKEN

      - name: Deploy dev-portal preview to Vercel
        id: deploy-dev-portal-preview
        working-directory: ./unified-docs-frontend-preview
        run: |
          dev_portal_preview=$(vercel deploy --prebuilt --scope=hashicorp --token=$VERCEL_TOKEN)
          echo "dev-portal-preview=$dev_portal_preview" >> $GITHUB_OUTPUT

      - name: Comment on PR with Preview URLs
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
        with:
          header: preview-notice
          message: |
            ## Preview URLs
            | Status | Preview | 
            | :------ | :------ |
            | ✅ Ready | [Unified docs](${{ steps.deploy-unified-docs.outputs.unified-docs-preview-url }})
            | ✅ Ready | [Dev portal](${{ steps.deploy-dev-portal-preview.outputs.dev-portal-preview }})

            ([Inspect Build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))