name: Build dev-portal Preview for PR
run-name: 'Build dev-portal preview for PR ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})'

on: pull_request

jobs:
  deploy-dev-portal-preview:
    name: Deploy Dev Portal Preview
    runs-on: ubuntu-latest
    steps:
    - name: Comment on PR
      if: github.event_name == 'pull_request_target'
      uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
      with:
        header: preview-notice
        message: |
            Deploying preview...

            | Preview | Status | Updated |
            | :------ | :------ | :------- |
            |         | 🔄 Building ([Inspect](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})) |    |
    - uses: actions/checkout@v4
    - name: Get Unified Docs API URL
      uses: ./.github/actions/get-vercel-preview-url
      id: unified_docs_preview_url
      with:
          project-name: web-presence-experimental-docs
          scope: hashicorp

    - name: Checkout hashicorp/dev-portal (Frontend)
      uses: actions/checkout@v4
      with:
        repository: hashicorp/dev-portal
        path: ./unified-docs-frontend-preview

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'unified-docs-frontend-preview/package-lock.json'

    - name: Setup Vercel CLI
      run: npm i --global vercel@latest

    - name: Pull preview environment
      run: vercel pull --yes --environment=preview --scope=hashicorp --token=${{ secrets.VERCEL_TOKEN }}
      working-directory: unified-docs-frontend-preview

    - name: Build dev-portal
      env:
        HASHI_ENV: preview
        MKTG_CONTENT_DOCS_API: https://content.hashicorp.com
        UNIFIED_DOCS_API: 'https://${{ steps.unified_docs_preview_url.outputs.preview-url }}'
        IS_CONTENT_PREVIEW: true
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      working-directory: unified-docs-frontend-preview

    - name: Deploy preview
      run: vercel deploy --prebuilt --scope=hashicorp --token=${{ secrets.VERCEL_TOKEN }}
      working-directory: unified-docs-frontend-preview
    - name: Get Date
      id: date
      run: echo "date=$(date)" >> $GITHUB_OUTPUT
    - name: Comment on PR
      if: github.event_name == 'pull_request_target'
      uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
      with:
        header: preview-notice
        message: |
          Preview Deployed!

          | Preview | Status | Updated |
          | :------ | :------ | :------- |
          | [${{ steps.unified_docs_preview_url.outputs.preview-url }}](https://${{ steps.unified_docs_preview_url.outputs.preview-url }}) | ✅ Ready ([Inspect](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})) | ${{ steps.date.outputs.date }} |