name: Trigger production deployment for Dev Portal

on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/**'
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy-dev-portal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hashicorp/web-unified-docs
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Get Unified Docs Vercel Data
        uses: ./.github/actions/get-vercel-preview-data
        id: unified_docs_preview_url
        with:
          deployment_type: 'id'
          project_id: ${{ secrets.VERCEL_UNIFIED_DOCS_PROJECT_ID }}
          team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          github_sha: ${{ github.event.pull_request.head.sha }} # the SHA of last commit on the PR branch

      - name: Checkout hashicorp/dev-portal (Frontend)
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: hashicorp/dev-portal
          path: ./unified-docs-frontend-preview

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'unified-docs-frontend-preview/package-lock.json'

      - name: Setup Vercel CLI
        run: npm i --global vercel@latest

      - run: vercel pull --yes --environment=preview --scope=hashicorp --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: unified-docs-frontend-preview

      - name: Wait for Unified Docs API to be ready
        uses: ./.github/actions/get-vercel-preview-data
        id: check_unified_docs_preview_url
        with:
          deployment_type: 'check'
          deployment_url: ${{ steps.unified_docs_preview_url.outputs.preview_url }}
          team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          num_of_checks: 3
          mins_between_checks: 5

      - name: re-deploy dev portal production
        # run: curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_PROD }}
        run: curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_TEST }}
