name: Deploy Dev Portal - Production

on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/**'
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy-udr:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }} # The org id for HashiCorp in Vercel
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # The ID of the UDR Vercel project
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --logs

  deploy-dev-portal:
    runs-on: ubuntu-latest
    needs: [deploy-udr]
    steps:
      - name: deploy dev portal production
        run: curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_PROD }}
