name: Build and Deploy Preview
run-name: 'Build and Deploy Preview for PR ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})'

on:
  pull_request

env:
  DEV_PORTAL_ID: prj_kxbbGoGdwKkIuEsMRVwetBX5lmgg
  VERCEL_TEAM_ID: team_kRChqe754SOcJudYPP6rroKH
  VERCEL_UNIFIED_DOCS_ID: prj_8gMrDMdPkLtKYwOEEdJLfuGXNEYF

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Vercel CLI
        run: npm i --global vercel@latest

      - name: Deploy Web Unified Docs preview
        id: deploy_web_unified_docs
        run: |
          UNIFIED_DOCS_DEPLOY_URL=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --scope=hashicorp --yes)
          echo "UNIFIED_DOCS_DEPLOY_URL=$UNIFIED_DOCS_DEPLOY_URL" >> $GITHUB_OUTPUT

      - name: Checkout hashicorp/dev-portal (Frontend)
        uses: actions/checkout@v4
        with:
          repository: hashicorp/dev-portal
          path: ./unified-docs-frontend-preview

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'unified-docs-frontend-preview/package-lock.json'

      - name: Pull Vercel environment for frontend
        run: vercel pull --yes --environment=preview --scope=hashicorp --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: unified-docs-frontend-preview

      - name: Build dev-portal and set environment variables
        env:
          HASHI_ENV: preview
          UNIFIED_DOCS_API: https://${{ env.UNIFIED_DOCS_DEPLOY_URL }}
          IS_CONTENT_PREVIEW: true
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: unified-docs-frontend-preview

      - name: Deploy Dev Portal
        run: |
          DEV_PORTAL_PREVIEW=$(vercel deploy --prebuilt --scope=hashicorp --token=${{ secrets.VERCEL_TOKEN }})
          echo "DEV_PORTAL_PREVIEW=$DEV_PORTAL_PREVIEW" >> $GITHUB_OUTPUT
        working-directory: unified-docs-frontend-preview

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
        if: github.event_name == 'pull_request'
        with:
          header: 'Preview URLs'
          message: |
            - [Unified Docs](${{ env.UNIFIED_DOCS_DEPLOY_URL }})
            - [Dev Portal](${{ env.DEV_PORTAL_PREVIEW }})