name: Build dev-portal Preview for PR
run-name: 'Build dev-portal preview for PR ${{ github.event.pull_request.number }}'

on:
  pull_request
env:
  DEV_PORTAL_ID: prj_kxbbGoGdwKkIuEsMRVwetBX5lmgg
  TEAM_ID: team_kRChqe754SOcJudYPP6rroKH

jobs:
  deploy-dev-portal-preview:
    name: Deploy Dev Portal Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hashicorp/dev-portal (Frontend)
        uses: actions/checkout@v4
        with:
          repository: hashicorp/dev-portal
          path: ./dev-portal-frontend

      - name: Get Unified Docs API URL
        run: |
          api_preview_url="https://web-presence-experimental-docs-git-rnno-versio-88eb75-hashicorp.vercel.app/"
          echo "API_PREVIEW_URL=${api_preview_url}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'dev-portal-frontend/package-lock.json'

      - name: Setup Vercel CLI
        run: npm i --global vercel@latest

      - run: vercel pull --yes --environment=preview --scope=hashicorp --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: dev-portal-frontend

      - name: Build dev-portal
        env:
          HASHI_ENV: preview
          MKTG_CONTENT_DOCS_API: https://content.hashicorp.com
          UNIFIED_DOCS_API: ${{ env.API_PREVIEW_URL }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: dev-portal-frontend

      - name: Deploy preview
        run: vercel deploy --prebuilt --scope=hashicorp --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: dev-portal-frontend
