name: Checkout Release Branches

on:
  - pull_request
  # schedule:
  #   - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  list-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.set-tags-output.outputs.tags }}
    strategy:
      matrix:
        repo: [
            terraform,
            # terraform-cdk,
            # terraform-docs-agents,
            # terraform-docs-common,
            # terraform-plugin-framework,
            # terraform-plugin-log,
            # terraform-plugin-mux,
            # terraform-plugin-sdk,
            # terraform-plugin-testing,
          ]

    steps:
      - name: List all tags
        id: list-tags
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const tags = await github.rest.repos.listTags({
              owner: 'hashicorp',
              repo: '${{ matrix.repo }}',
            });
            return JSON.stringify(tags.data.map(tag => tag.name));

      - name: Set tags output
        id: set-tags-output
        run: echo "tags=${{ steps.list-tags.outputs.result }}" >> $GITHUB_ENV

  checkout-tags:
    needs: list-tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJSON(needs.list-tags.outputs.tags) }}

    steps:
      - name: Checkout repository at specific tag
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: hashicorp/${{ matrix.repo }}
          ref: ${{ matrix.tag }}
          fetch-depth: 0
          fetch-tags: true
          path: website
          sparse-checkout: website

      - name: Get changed files
        id: changed-files
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const changedFiles = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            return changedFiles.data.map(file => file.filename).join('\n');

      - name: Add changed files to job summary
        run: echo "Changed files:\n${{ steps.changed-files.outputs.result }}" >> $GITHUB_STEP_SUMMARY

    #   - name: Create Pull Request
    #     uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
    #     with:
    #       # Git commit details
    #       branch: automation/docs-sync
    #       commit-message: |-
    #         sync docs from ${{ matrix.repo }}@${{ matrix.tag }}
    #       # Pull Request details
    #       title: 'Automated PR to sync docs'
    #       body: |-
    #         This PR is automatically generated to sync the docs from ${{ matrix.repo }}@${{ matrix.tag }}.
    #       labels: dependencies,auto-approve,ci/run-all
    #       team-reviewers: cdktf
    #       token: ${{ secrets.TERRAFORM_CDK_PUSH_GITHUB_TOKEN }}
