# Apply a product label based on the content files modified in the pull request
# and configuration details in .github/labeler.yml.
#
# For more information, see: https://github.com/actions/labeler

name: 🏷️ Label content PRs

on: [pull_request_target]

jobs:

  label-the-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
