name: On Demand ISR

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  on-demand-isr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get Unified Docs Vercel Data
        uses: ./.github/actions/get-vercel-preview-data
        id: unified_docs_preview_url
        with:
          deployment_type: 'id'
          project_id: ${{ secrets.VERCEL_UNIFIED_DOCS_PROJECT_ID }}
          team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          github_sha: ${{ github.event.pull_request.base.sha }} # the SHA of last commit on main

      # - name: Wait for Unified Docs API to be ready
      #   uses: ./.github/actions/get-vercel-preview-data
      #   id: check_unified_docs_preview_url
      #   with:
      #     deployment_type: 'check'
      #     deployment_url: 'https://web-unified-docs-hashicorp.vercel.app/'
      #     team_id: ${{ secrets.VERCEL_TEAM_ID }}
      #     vercel_token: ${{ secrets.VERCEL_TOKEN }}
      #     num_of_checks: 3
      #     mins_between_checks: 5

      # - name: Get changed files in the content/ subdirectories
      #   id: changed-files
      #   uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
      #   with:
      #     files: |
      #       content/**/*.mdx

      # - name: Print changed files
      #   run: |
      #     echo "Changed files:"
      #     echo ${{ steps.changed-files.outputs.all_changed_files }}

      # - name: Map files to URLs
      #   id: map-files
      #   uses: ./.github/actions/map-files
      #   with:
      #     files: ${{ steps.changed-files.outputs.all_changed_files }}
       
      # - name: Revalidate paths
      #   id: revalidate-paths
      #   env:
      #     url: 'https://developer.hashicorp.com/api/revalidate/paths'
      #     auth: 'Authorization: Bearer ${{ secrets.DEVELOPER_REVALIDATE_TOKEN }}'
      #   run: |
      #     curl -sS -X POST "${{ env.url }}" \
      #       -H "${{ env.auth }}" \
      #       -H "Content-Type: application/json" \
      #       -d "{\"path\": \"${{ steps.map-files.outputs.paths }}\" }" | jq .