name: On Demand ISR

on:
  workflow_dispatch:

jobs:
  on-demand-isr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files in the content/ subdirectories
        id: changed-files
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
        with:
          files: |
            content/**/*.mdx

      - name: Print changed files
        run: |
          echo "Changed files:"
          echo ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Map files to URLs
        id: map-files
        uses: ./.github/actions/map-files-to-urls
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Print urls
        run: echo ${{ steps.map-files.outputs.paths }}
       
      # - name: Revalidate paths
      #   id: revalidate-paths
      #   env:
      #     url: 'https://developer.hashicorp.com/api/revalidate/paths'
      #     auth: 'Authorization: Bearer ${{ secrets.DEVELOPER_REVALIDATE_TOKEN }}'
      #   run: |
      #     curl -sS -X POST "${{ env.url }}" \
      #       -H "${{ env.auth }}" \
      #       -H "Content-Type: application/json" \
      #       -d "{\"path\": \"${{ steps.map-files.outputs.paths }}\" }" | jq .