name: Re-load dev portal

on:
  workflow_dispatch:
    inputs:
      base_sha:
        description: 'Base SHA for changed files comparison'
        required: true
        type: string
      head_sha:
        description: 'Head SHA for changed files comparison'
        required: true
        type: string

jobs:
  re-load-dev-portal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        run: npm install

      - name: Run prebuild script
        run: npm run prebuild

      - name: Re-load dev portal
        uses: ./.github/actions/re-load-dev-portal
        with:
          base_sha: ${{ inputs.base_sha }}
          head_sha: ${{ inputs.head_sha }}