name: Trigger production deployment for Dev Portal

on:
  push:
    branches:
      - 'heat/chore/dev-portal-deploy-gha'
    paths:
      - 'content/**'
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy-dev-portal:
    runs-on: ubuntu-latest
    steps:
      # TODO: Temporary workaround
      - name: wait 10 minutes
        run: sleep 600

      - name: re-deploy dev portal production
        # run: curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_PROD }}
        run: curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_TEST }}
