name: Trigger production deployment for Dev Portal

on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/**'
      - 'app/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev-portal:
    runs-on: ubuntu-latest
    steps:
      # TODO: Temporary workaround
      - name: wait 5 minutes
        run: sleep 300

      - name: re-deploy dev portal production
        run: curl -X POST ${{ secrets.DEV_PORTAL_DEPLOY_HOOK_PROD }}
