name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [workflow_dispatch]

jobs:
  Sync-Vault-Release-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🚧 ${{ github.repository }} - Syncing Vault release branch with main"
          echo "    - Trigger event: ${{ github.event_name }}"
          echo "    - Branch:        ${{ github.ref }}"
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
