name: Sync content release branches

run-name: 🚀 ${{ github.actor }} is syncing ${{ github.event.inputs.product }} release branches

on: 
  workflow_dispatch:
    inputs:
      product:
        required: true
        default: 'vault'
        description: >-
          Product slug (e.g., vault, hcp)

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      mylist: ${{ steps.generate-matrix.outputs.mylist }}
    steps:
      - name: Generate dynamic matrix
        id: generate-matrix
        run: |
          echo "mylist=[$(for i in {1..2}; do  echo -n "$i," ; done)3]" >> $GITHUB_OUTPUT
  usematrix:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        branch-name: ${{ fromJson(needs.build.outputs.mylist) }}
    steps:
      - name: Dynamic matrix job
        run: |
          echo "Running job with input ${{ matrix.branch-name }}"