name: Sync content release branches

run-name: 🚀 ${{ github.actor }} is syncing ${{ github.event.inputs.product }} release branches

on: 
  workflow_dispatch:
    branches: [main]
    inputs:
      product:
        required: true
        default: 'vault'
        description: >-
          Product slug (e.g., vault, hcp)

permissions: 
  contents: write

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.gen_output.outputs.output_1 }}
      output_2: ${{ steps.gen_output.outputs.output_2 }}
      output_3: ${{ steps.gen_output.outputs.output_3 }}
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - name: Generate output
        id: gen_output
        run: |
          version="${{ matrix.version }}"
          echo "output_${version}=${version}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo '${{ toJSON(needs.job1.outputs) }}'