name: 'Tests'
run-name: 'GHA to upload build artifact as part of test flow'

on:
  pull_request:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'
  push:
    branches: ['heat/test']

jobs:
  test:
    name: 'Upload artifact and run tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        id: upload-build-artifact
        with:
          name: build-artifact
          path: |
            /home/runner/work/web-unified-docs/web-unified-docs
            .next
          overwrite: true
          retention-days: 5

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'

      - run: npm ci
      - run: npm run prebuild
      - run: npm run test
