name: Trigger Repo Sync in Other Repo

on:
  push:
    branches: [main]

jobs:
  dispatch_workflow:
    if: github.repository == 'hashicorp/web-unified-docs-internal' || github.repository == 'hashicorp/web-unified-docs'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow in target repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: hashicorp/${{ github.repository == 'hashicorp/web-unified-docs-internal' && 'web-unified-docs' || 'web-unified-docs-internal' }}
          event-type: push-repo-sync
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}"
            }
