# Add comments to Vault PRs with a reminder about release branches
# github.base_ref (target)
# github.head_ref (source)

name: Process Vault PR
run-name: 🚀 Processing Vault PR

on: [pull_request_target]

env:
  yes: ✔️
  no: ❌
  comment_text: |
    ## 🕛 Publication timeline

    Content changes publish based on the merge target [`${{ github.base_ref }}`]

    Branch            | Publication timeline  | Selection
    ----------------- | --------------------- | ---------
    `main`            | Immediately           | ⏹️
    `vault/YYYYMM`    | End of the month      | ⏹️
    `vault/<version>` | Next major release    | ⏹️

jobs:

  add-pub-comment:
    name: Add initial comment
    runs-on: ubuntu-latest

    steps:
      - name: Initial comment on PR
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          header: Publication notice
          message: ${{ github.env.comment_text }}

  set-pub-timeline:
    name: Make timeline selection
    runs-on: ubuntu-latest
    outputs:
      main_select: ${{ steps.check-main.outputs.main_select }}
      month_select: ${{ steps.check-month.outputs.month_select }}
      release_select: ${{ steps.check-release.outputs.release_select }}
    steps:
      - name: PR publishes immediately
        id: check-main
        if: ${{ github.base_ref }} == "main"
        run: |
          echo "main_select=${{ env.yes }}" >> "$GITHUB_OUTPUT"

      - name: PR publishes with monthly release
        id: check-month
        if: ${{ github.base_ref }} ~= "vault/[0-9]{6}"
        run: |
          echo "month_select=${{ env.yes }}" >> "$GITHUB_OUTPUT"

      - name: PR publishes with next major release
        id: check-release
        if: ${{ github.base_ref }} ~= "vault/[0-9]\\.[0-9]{2}\\.x"
        run: |
          echo "release_select=${{ env.yes }}" >> "$GITHUB_OUTPUT"

  update-pub-timeline:
    runs-on: ubuntu-latest
    needs: set-pub-timeline
    steps:
      - name: Update publication notice
        if: ${{ github.base_ref }} ~= "vault/[0-9]\\.[0-9]{2}\\.x"
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          header: Publication notice
          message: |
          ${{ github.env.pub_comment }}
      - env:
        main_select: ${{ needs.set-pub-timeline.outputs.main_select }}
        month_select: ${{ needs.set-pub-timeline.outputs.month_select }}
        release_select: ${{ needs.set-pub-timeline.outputs.release_select }}