# Add comments to Vault PRs with a reminder about release branches
# github.base_ref (target)
# github.head_ref (source)

name: Process Vault PR
run-name: 🚀 Processing Vault PR

on: [pull_request_target]

env:
  yes: ✔️
  no: ❌
  idk: ⏹️
  main_select: "idk"
  month_select: "idk"
  release_select: "idk"
jobs:

  set-pub-timeline:
    name: Make timeline selection
    runs-on: ubuntu-latest
    steps:
      - name: Set defaults
        id: set-defaults
        run: |
          echo "main_select=${{ github.env.idk }}" >> "$GITHUB_ENV"
          echo "month_select=${{ github.env.idk }}" >> "$GITHUB_ENV"
          echo "release_select=${{ github.env.idk }}" >> "$GITHUB_ENV"
      - name: Check main
        id: check-main
        if: ${{ github.base_ref }} == "main"
        run: |
          echo "main_select=${{ env.yes }}" >> "$GITHUB_ENV"
      - name: Check monthly update
        id: check-monthly
        if: ${{ github.base_ref }} ~= "vault/[0-9]{6}"
        run: |
          echo "month_select=${{ env.yes }}" >> "$GITHUB_ENV"
      - name: Check release
        id: check-release
        if: ${{ github.base_ref }} ~= "vault/[0-9]\\.[0-9]{2}\\.x"
        run: |
          echo "release_select=${{ env.yes }}" >> "$GITHUB_ENV"

  alert-pub-timeline:
    name: Add publication alert
    env:
      local_comment:  |
        ## 🕛 Publication timeline

        Content changes publish based on the merge target [`${{ github.base_ref }}`]

        Branch            | Publication timeline  | Selection
        ----------------- | --------------------- | ---------
        `main`            | Immediately           | ${{ github.env.main_select }}
        `vault/YYYYMM`    | End of the month      | ${{ github.env.month_select }}
        `vault/<version>` | Next major release    | ${{ github.env.release_select }}
    runs-on: ubuntu-latest
    needs: set-pub-timeline
    steps:
      - name: Add publication notice
        if: ${{ github.base_ref }} ~= "vault/[0-9]\\.[0-9]{2}\\.x"
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          header: Publication notice
          message: ${{ env.local_comment }}