# Add comments to Vault PRs with a reminder about release branches
# github.base_ref (target)
# github.head_ref (source)

name: Process Vault PR
run-name: 🚀 Processing Vault PR

on: [pull_request_target]

env:
  yes: ✔️
  no: ❌
  idk: ⏹️
  monthlyPattern: 'vault/([0-9]{6})'
  releasePattern: 'vault/1\.([0-9]{2})\.x'
jobs:

  set-timeline:
    name: Make timeline selection
    runs-on: ubuntu-latest
    outputs:
      main_select: ${{ steps.check-target.outputs.main_select }}
      month_select: ${{ steps.check-target.outputs.month_select }}
      release_select: ${{ steps.check-target.outputs.release_select }}
    steps:
      - name: Check target
        id: check-target
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "main_select=${{ env.yes }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.no }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.no }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.base_ref }}" =~ ${{ env.monthlyPattern }}  ]]; then
            echo "main_select=${{ env.no }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.yes }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.no }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.base_ref }}" =~ ${{ env.releasePattern }} ]]; then
            echo "main_select=${{ env.no }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.no }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.yes }}" >> "$GITHUB_OUTPUT"
          else
            echo "main_select=${{ env.idk }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.idk }}" >> "$GITHUB_OUTPUT"
            echo "month_select=${{ env.idk }}" >> "$GITHUB_OUTPUT"
          fi

  alert-pub-timeline:
    runs-on: ubuntu-latest
    needs: set-timeline
    steps:
      - name: Add publication notice
        if: ${{ github.base_ref }} ~= "vault/[0-9]\\.[0-9]{2}\\.x"
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        with:
          header: Publication notice
          message: |
            ## 🕛 Publication timeline

            Content changes publish based on the merge target [`${{ github.base_ref }}`]

            Branch            | Publication timeline  | Selection
            ----------------- | --------------------- | ---------
            `main`            | Immediately           | ${{ needs.set-timeline.outputs.main_select }}
            `vault/YYYYMM`    | End of the month      | ${{ needs.set-timeline.outputs.month_select }}
            `vault/<version>` | Next major release    | ${{ needs.set-timeline.outputs.release_select }}